services:
  chatwave:
    image: ghcr.io/lifufkd/chatwave:latest
    build: .
    restart: unless-stopped
    volumes:
      - app_data:${MEDIA_FOLDER:-/app/data}
    env_file:
      - "${ENV_FILE:-.env}"
    environment:
      - DB_HOST=postgres
      - DB_USER=${DB_USER:?DB_USER is required}
      - DB_PASSWORD=${DB_PASSWORD:?DB_PASSWORD is required}
      - DB_DATABASE=${DB_DATABASE:-postgres}
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD:?REDIS_PASSWORD is required}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:?JWT_SECRET_KEY is required}
      - API_CORS_ALLOW_ORIGINS=${API_CORS_ALLOW_ORIGINS:?API_CORS_ALLOW_ORIGINS is required}
      - MODE=production
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    mem_limit: 1g
    cpus: 2.0
    networks:
      - backend

  web:
    image: ghcr.io/lifufkd/chatwave-web:latest
    restart: unless-stopped
    ports:
      - ${HTTP_WEB_PORT:-80}:80
      - ${HTTPS_WEB_PORT:-443}:443
    volumes:
      - ${SSL_CERTS_FOLDER}:/cert:ro
    env_file:
      - "${ENV_FILE:-.env}"
    depends_on:
      - chatwave
    networks:
      - backend

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    restart: unless-stopped
    ports:
      - ${API_PORT:-4433}:443
    volumes:
      - ${SSL_CERTS_FOLDER}:/cert:ro
    env_file:
      - "${ENV_FILE:-.env}"
    depends_on:
      - chatwave
    networks:
      - backend

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
       - POSTGRES_USER=${DB_USER:?DB_USER is required}
       - POSTGRES_PASSWORD=${DB_PASSWORD:?DB_PASSWORD is required}
       - POSTGRES_DB=${DB_DATABASE:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.4-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD:?REDIS_PASSWORD is required}"]
    volumes:
      - redis_data:/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a $$REDIS_PASSWORD ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:?REDIS_PASSWORD is required}

volumes:
  postgres_data:
  redis_data:
  app_data:

networks:
  backend:
