"""add created status to messages table

Revision ID: 8837bec2b062
Revises: da4d4438e254
Create Date: 2025-01-20 23:45:47.492324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from utilities import db_settings

# revision identifiers, used by Alembic.
revision: str = '8837bec2b062'
down_revision: Union[str, None] = 'da4d4438e254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema=db_settings.DB_SCHEMA,
        enum_name='messagesstatus',
        new_values=['CREATED', 'SENT', 'DELIVERED', 'READ'],
        affected_columns=[
            TableReference(
                table_schema=db_settings.DB_SCHEMA,
                table_name='messages',
                column_name='status',
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema=db_settings.DB_SCHEMA,
        enum_name='messagesstatus',
        new_values=['SENT', 'DELIVERED', 'READ'],
        affected_columns=[
            TableReference(
                table_schema=db_settings.DB_SCHEMA,
                table_name='messages',
                column_name='status',
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
